version: '3.7'

services:
  postgres:
    image: postgres:14.1
    container_name: go_web_api_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - PGDATA=/data/postgres
      - POSTGRES_DB=car_sales
    volumes:
      - postgres:/data/postgres
    ports:
      - "5434:5432"
    networks:
      - golang_web_api_nt
    restart: unless-stopped
  
  redis:
    image: redis:7
    container_name: go_web_api_redis
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
      - redis:/etc/redis.conf
      - redis:/data
    ports:
      - "6379:6379"
    networks:
      - golang_web_api_nt


volumes:
  postgres:
  redis:
  logs:


networks:
  golang_web_api_nt:
    driver:  bridge